#!/usr/bin/bash

# Check if exactly one argument is provided; if so, use it as the selected directory
if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Otherwise, use fzf to interactively select a directory under the home directory
    selected=$(find ~/ -maxdepth 1 -type d | fzf)
fi

# If no directory is selected (empty), exit gracefully
if [[ -z $selected ]]; then
    exit 0
fi

# Extract the base name of the selected directory and replace '.' with '_' (for tmux session name)
selected_name=$(basename "$selected" | tr . _)

# Check if tmux is already running
tmux_running=$(pgrep tmux)

# If not inside tmux and tmux is not already running, start a new session with the selected directory
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

# If tmux session with selected_name does not exist, create a new detached session with the selected directory
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

# Switch to the tmux session with the selected_name
tmux switch-client -t $selected_name
