import = [
  "~/.config/alacritty/catpuccin-mocha.toml"  # Import additional configuration
]

[env]
TERM = "xterm-256color"  # Set terminal type

[window]
padding = { x = 5, y = 5 }  # Set padding around the window
decorations = "None"  # Disable window decorations (title bar, borders)
opacity = 1.0  # Set window opacity to 100%
startup_mode = "Maximized"  # Start the window maximized

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }  # Set default font family and style

[mouse]
hide_when_typing = true  # Hide mouse cursor when typing
