import = [
  "~/.config/alacritty/catpuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }

[mouse]
hide_when_typing = true
